// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const agentExists = `-- name: AgentExists :one
SELECT EXISTS(SELECT 1 FROM agents WHERE id = $1)
`

func (q *Queries) AgentExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, agentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAgent = `-- name: CreateAgent :one

INSERT INTO agents (id, created_at) VALUES ($1, now())
RETURNING id, created_at
`

// Queries for the `agents` table. See ALL_DESIGN_IMPLEMENTATION/sql-metadata-plan.md §12.
func (q *Queries) CreateAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent, id)
	var i Agent
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAllAgentIDs = `-- name: ListAllAgentIDs :many
SELECT id FROM agents
`

// Used once at startup to warm the agent-existence sync.Map.
func (q *Queries) ListAllAgentIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllAgentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
