// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const conversationExists = `-- name: ConversationExists :one
SELECT EXISTS(SELECT 1 FROM conversations WHERE id = $1)
`

func (q *Queries) ConversationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, conversationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createConversation = `-- name: CreateConversation :exec

INSERT INTO conversations (id, s2_stream_name, head_seq, created_at)
VALUES ($1, $2, 0, now())
`

type CreateConversationParams struct {
	ID           uuid.UUID `json:"id"`
	S2StreamName string    `json:"s2_stream_name"`
}

// Queries for the `conversations` table. See sql-metadata-plan.md §12.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.Exec(ctx, createConversation, arg.ID, arg.S2StreamName)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, s2_stream_name, head_seq, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.S2StreamName,
		&i.HeadSeq,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationHeadSeq = `-- name: GetConversationHeadSeq :one
SELECT head_seq FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationHeadSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationHeadSeq, id)
	var head_seq int64
	err := row.Scan(&head_seq)
	return head_seq, err
}

const updateConversationHeadSeq = `-- name: UpdateConversationHeadSeq :exec
UPDATE conversations
SET head_seq = $2
WHERE id = $1 AND head_seq < $2
`

type UpdateConversationHeadSeqParams struct {
	ID      uuid.UUID `json:"id"`
	HeadSeq int64     `json:"head_seq"`
}

// Regression-guarded. An out-of-order write cannot rewind head_seq.
func (q *Queries) UpdateConversationHeadSeq(ctx context.Context, arg UpdateConversationHeadSeqParams) error {
	_, err := q.db.Exec(ctx, updateConversationHeadSeq, arg.ID, arg.HeadSeq)
	return err
}
