// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cursors.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const ackCursor = `-- name: AckCursor :exec
INSERT INTO cursors (agent_id, conversation_id, ack_seq, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (agent_id, conversation_id)
DO UPDATE SET ack_seq = EXCLUDED.ack_seq, updated_at = EXCLUDED.updated_at
WHERE cursors.ack_seq < EXCLUDED.ack_seq
`

type AckCursorParams struct {
	AgentID        uuid.UUID `json:"agent_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	AckSeq         int64     `json:"ack_seq"`
}

// Synchronous write-through UPSERT for POST /conversations/:cid/ack.
// Does NOT touch delivery_seq. Regression-guarded.
func (q *Queries) AckCursor(ctx context.Context, arg AckCursorParams) error {
	_, err := q.db.Exec(ctx, ackCursor, arg.AgentID, arg.ConversationID, arg.AckSeq)
	return err
}

const getAckCursor = `-- name: GetAckCursor :one
SELECT ack_seq FROM cursors
WHERE agent_id = $1 AND conversation_id = $2
`

type GetAckCursorParams struct {
	AgentID        uuid.UUID `json:"agent_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

func (q *Queries) GetAckCursor(ctx context.Context, arg GetAckCursorParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAckCursor, arg.AgentID, arg.ConversationID)
	var ack_seq int64
	err := row.Scan(&ack_seq)
	return ack_seq, err
}

const getDeliveryCursor = `-- name: GetDeliveryCursor :one

SELECT delivery_seq FROM cursors
WHERE agent_id = $1 AND conversation_id = $2
`

type GetDeliveryCursorParams struct {
	AgentID        uuid.UUID `json:"agent_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

// Queries for the `cursors` table. See sql-metadata-plan.md §7 and §12.
func (q *Queries) GetDeliveryCursor(ctx context.Context, arg GetDeliveryCursorParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDeliveryCursor, arg.AgentID, arg.ConversationID)
	var delivery_seq int64
	err := row.Scan(&delivery_seq)
	return delivery_seq, err
}

const listUnreadForAgent = `-- name: ListUnreadForAgent :many
SELECT c.id                                   AS conversation_id,
       c.head_seq                             AS head_seq,
       COALESCE(k.ack_seq, 0)::bigint         AS ack_seq,
       (c.head_seq - COALESCE(k.ack_seq, 0))::bigint AS event_delta
FROM members m
JOIN conversations c ON c.id = m.conversation_id
LEFT JOIN cursors k
       ON k.agent_id = m.agent_id
      AND k.conversation_id = m.conversation_id
WHERE m.agent_id = $1
  AND c.head_seq > COALESCE(k.ack_seq, 0)
ORDER BY c.head_seq DESC
LIMIT $2
`

type ListUnreadForAgentParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

type ListUnreadForAgentRow struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	HeadSeq        int64     `json:"head_seq"`
	AckSeq         int64     `json:"ack_seq"`
	EventDelta     int64     `json:"event_delta"`
}

// Single indexed join powering GET /agents/me/unread.
func (q *Queries) ListUnreadForAgent(ctx context.Context, arg ListUnreadForAgentParams) ([]ListUnreadForAgentRow, error) {
	rows, err := q.db.Query(ctx, listUnreadForAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadForAgentRow{}
	for rows.Next() {
		var i ListUnreadForAgentRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.HeadSeq,
			&i.AckSeq,
			&i.EventDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeliveryCursor = `-- name: UpsertDeliveryCursor :exec
INSERT INTO cursors (agent_id, conversation_id, delivery_seq, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (agent_id, conversation_id)
DO UPDATE SET delivery_seq = EXCLUDED.delivery_seq, updated_at = EXCLUDED.updated_at
WHERE cursors.delivery_seq < EXCLUDED.delivery_seq
`

type UpsertDeliveryCursorParams struct {
	AgentID        uuid.UUID `json:"agent_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	DeliverySeq    int64     `json:"delivery_seq"`
}

// Single-row delivery_seq UPSERT for disconnect/leave/shutdown flush.
// Regression-guarded: a stale/out-of-order write is a silent no-op.
// Does NOT touch ack_seq.
func (q *Queries) UpsertDeliveryCursor(ctx context.Context, arg UpsertDeliveryCursorParams) error {
	_, err := q.db.Exec(ctx, upsertDeliveryCursor, arg.AgentID, arg.ConversationID, arg.DeliverySeq)
	return err
}
