// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dedup.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMessageDedup = `-- name: GetMessageDedup :one

SELECT status, start_seq, end_seq
FROM messages_dedup
WHERE conversation_id = $1 AND message_id = $2
`

type GetMessageDedupParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MessageID      uuid.UUID `json:"message_id"`
}

type GetMessageDedupRow struct {
	Status   string `json:"status"`
	StartSeq *int64 `json:"start_seq"`
	EndSeq   *int64 `json:"end_seq"`
}

// Queries for the `messages_dedup` table. See sql-metadata-plan.md §12.
// Write-path idempotency lookup. Called at the very start of both message-write
// handlers. On hit, the handler replays the cached terminal outcome instead
// of writing to S2 again.
func (q *Queries) GetMessageDedup(ctx context.Context, arg GetMessageDedupParams) (GetMessageDedupRow, error) {
	row := q.db.QueryRow(ctx, getMessageDedup, arg.ConversationID, arg.MessageID)
	var i GetMessageDedupRow
	err := row.Scan(&i.Status, &i.StartSeq, &i.EndSeq)
	return i, err
}

const insertMessageDedupComplete = `-- name: InsertMessageDedupComplete :exec
INSERT INTO messages_dedup (conversation_id, message_id, status, start_seq, end_seq)
VALUES ($1, $2, 'complete', $3, $4)
ON CONFLICT (conversation_id, message_id) DO NOTHING
`

type InsertMessageDedupCompleteParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	MessageID      uuid.UUID `json:"message_id"`
	StartSeq       *int64    `json:"start_seq"`
	EndSeq         *int64    `json:"end_seq"`
}

// Called after a successful S2 append of message_start + appends + message_end.
// ON CONFLICT DO NOTHING: first writer wins; a concurrent sweeper becomes a no-op.
func (q *Queries) InsertMessageDedupComplete(ctx context.Context, arg InsertMessageDedupCompleteParams) error {
	_, err := q.db.Exec(ctx, insertMessageDedupComplete,
		arg.ConversationID,
		arg.MessageID,
		arg.StartSeq,
		arg.EndSeq,
	)
	return err
}
