// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: in_progress.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimInProgressMessage = `-- name: ClaimInProgressMessage :execrows

INSERT INTO in_progress_messages (message_id, conversation_id, agent_id, s2_stream_name, started_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (conversation_id, message_id) DO NOTHING
`

type ClaimInProgressMessageParams struct {
	MessageID      uuid.UUID `json:"message_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	AgentID        uuid.UUID `json:"agent_id"`
	S2StreamName   string    `json:"s2_stream_name"`
}

// Queries for the `in_progress_messages` table. See sql-metadata-plan.md §12.
// Atomic in-flight claim. Returns affected row count: 1 means this handler now
// owns (conversation_id, message_id); 0 means a concurrent writer or a
// crashed prior attempt already claimed it.
func (q *Queries) ClaimInProgressMessage(ctx context.Context, arg ClaimInProgressMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimInProgressMessage,
		arg.MessageID,
		arg.ConversationID,
		arg.AgentID,
		arg.S2StreamName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInProgressMessage = `-- name: DeleteInProgressMessage :exec
DELETE FROM in_progress_messages WHERE message_id = $1
`

func (q *Queries) DeleteInProgressMessage(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInProgressMessage, messageID)
	return err
}

const listInProgressMessages = `-- name: ListInProgressMessages :many
SELECT message_id, conversation_id, agent_id, s2_stream_name, started_at
FROM in_progress_messages
`

// Drained by the recovery sweep on server startup.
func (q *Queries) ListInProgressMessages(ctx context.Context) ([]InProgressMessage, error) {
	rows, err := q.db.Query(ctx, listInProgressMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InProgressMessage{}
	for rows.Next() {
		var i InProgressMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ConversationID,
			&i.AgentID,
			&i.S2StreamName,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
