// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :one

INSERT INTO members (conversation_id, agent_id, joined_at)
VALUES ($1, $2, now())
ON CONFLICT (conversation_id, agent_id) DO NOTHING
RETURNING conversation_id
`

type AddMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	AgentID        uuid.UUID `json:"agent_id"`
}

// Queries for the `members` table. See sql-metadata-plan.md §12.
// Idempotent insert. RETURNING conversation_id is non-empty when the row was
// newly added; empty (pgx.ErrNoRows) when the agent was already a member.
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addMember, arg.ConversationID, arg.AgentID)
	var conversation_id uuid.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS(
    SELECT 1 FROM members WHERE conversation_id = $1 AND agent_id = $2
)
`

type IsMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	AgentID        uuid.UUID `json:"agent_id"`
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.ConversationID, arg.AgentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationsForAgent = `-- name: ListConversationsForAgent :many
SELECT c.id, c.s2_stream_name, c.head_seq, c.created_at
FROM members m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.agent_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListConversationsForAgent(ctx context.Context, agentID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.S2StreamName,
			&i.HeadSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT agent_id FROM members WHERE conversation_id = $1 ORDER BY joined_at
`

func (q *Queries) ListMembers(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var agent_id uuid.UUID
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMembersForUpdate = `-- name: LockMembersForUpdate :many
SELECT agent_id FROM members WHERE conversation_id = $1 FOR UPDATE
`

// SELECT ... FOR UPDATE. Caller must run inside a transaction to keep the
// lock — postgres.go's RemoveMember does exactly that via pool.BeginTx.
func (q *Queries) LockMembersForUpdate(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockMembersForUpdate, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var agent_id uuid.UUID
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM members WHERE conversation_id = $1 AND agent_id = $2
`

type RemoveMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	AgentID        uuid.UUID `json:"agent_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ConversationID, arg.AgentID)
	return err
}
