// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID           uuid.UUID          `json:"id"`
	S2StreamName string             `json:"s2_stream_name"`
	HeadSeq      int64              `json:"head_seq"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Cursor struct {
	AgentID        uuid.UUID          `json:"agent_id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	DeliverySeq    int64              `json:"delivery_seq"`
	AckSeq         int64              `json:"ack_seq"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type InProgressMessage struct {
	MessageID      uuid.UUID          `json:"message_id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	AgentID        uuid.UUID          `json:"agent_id"`
	S2StreamName   string             `json:"s2_stream_name"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
}

type Member struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	AgentID        uuid.UUID          `json:"agent_id"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type MessagesDedup struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	MessageID      uuid.UUID          `json:"message_id"`
	Status         string             `json:"status"`
	StartSeq       *int64             `json:"start_seq"`
	EndSeq         *int64             `json:"end_seq"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
